[package]
name = "rusdd"
version = "0.1.0"
authors = ["Philipp Rosenberger <code@iluminat23.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33.3"
byte-unit = "~4.0.10"
parse_int = "0.5.0"